from __future__ import annotations

from pathlib import Path
from typing import Dict


def write_fake_agent(path: Path, script_name: str) -> None:
    script = path / script_name
    script.write_text(
        """#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import pathlib
import sys
import time


def _status_file() -> pathlib.Path:
    override = os.environ.get("STRINGBEAN_FAKE_STATE_PATH")
    if override:
        return pathlib.Path(override)
    cwd = pathlib.Path.cwd()
    return cwd.parent / f"{cwd.name}.stringbean-fake-state.json"


def _count(name: str) -> int:
    state = _status_file()
    values: Dict[str, int] = {}
    if state.exists():
        try:
            values = json.loads(state.read_text(encoding=\"utf-8\"))
        except Exception:
            values = {}
    values[name] = int(values.get(name, 0)) + 1
    state.write_text(json.dumps(values), encoding=\"utf-8\")
    return values[name]


def _write_result(payload):
    print("stream output start")
    print("```json")
    print(json.dumps(payload, indent=2))
    print("```")


role = os.environ.get("AGENT_ROLE", "orchestrator")
repo_root = pathlib.Path.cwd()

if os.environ.get("EMIT_STDERR_STATUS", "0") == "1":
    print(f"stderr status from {role}", file=sys.stderr)

if role == "planner":
    call = _count("planner")
    tasks = [
        {
            "id": "task-1",
            "title": "Initialize",
            "description": "Create initial artifacts",
            "dependencies": [],
            "recommended_role": "implementer",
            "permissions": "read_write",
            "verification": ["tests"],
        }
    ]
    if call > 1 and os.environ.get("PLAN_REVISION_ENABLED", "0") == "1":
        tasks.append(
            {
                "id": "task-2",
                "title": "Rework",
                "description": "Apply advisor feedback",
                "dependencies": ["task-1"],
                "recommended_role": "implementer",
                "permissions": "read_write",
                "verification": ["tests"],
            }
        )
    _write_result(
        {
            "summary": f"Plan generated by planner #{call}",
            "assumptions": [],
            "tasks": tasks,
            "risks": [],
            "advisor_questions": [],
        }
    )

elif role == "advisor":
    call = _count("advisor")
    if os.environ.get("ADVISOR_ALWAYS_REVISE", "0") == "1":
        _write_result(
            {
                "verdict": "revise",
                "severity": "medium",
                "summary": "Need changes",
                "blockers": [],
                "concerns": [],
                "recommendations": ["revise"],
            }
        )
    elif os.environ.get("ADVISOR_BLOCK", "0") == "1" and call == 1:
        _write_result(
            {
                "verdict": "block",
                "severity": "high",
                "summary": "blocked",
                "blockers": ["stop"],
                "concerns": [],
                "recommendations": [],
            }
        )
    else:
        _write_result(
            {
                "verdict": "approve",
                "severity": "none",
                "summary": "looks good",
                "blockers": [],
                "concerns": [],
                "recommendations": [],
            }
        )

elif role == "implementer":
    call = _count("implementer")
    if os.environ.get("IMPLEMENT_FAIL_FIRST", "0") == "1" and call == 1:
        print("simulate failing implementer")
        sys.exit(2)
    target = os.environ.get("IMPLEMENT_TARGET", "implemented.txt")
    (repo_root / target).write_text(f"updated by implementer #{call}\\n", encoding="utf-8")
    _write_result(
        {
            "status": "completed",
            "summary": f"done #{call}",
            "files_changed": [target],
            "commands_run": [],
            "tests": [],
            "remaining_issues": [],
            "handoff_notes": [],
        }
    )

elif role == "reviewer":
    call = _count("reviewer")
    seq = os.environ.get("REVIEW_SEQUENCE", "approve").split(",")
    choice = seq[min(call - 1, len(seq) - 1)] if seq else "approve"
    if choice == "changes_requested":
        _write_result(
            {
                "verdict": "changes_requested",
                "summary": "needs fixes",
                "blocking_issues": [],
                "non_blocking_issues": [],
                "required_fixes": ["do fix " + str(call)],
                "tests_recommended": [],
            }
        )
    elif choice == "reject":
        _write_result(
            {
                "verdict": "reject",
                "summary": "rejected",
                "blocking_issues": ["x"],
                "non_blocking_issues": [],
                "required_fixes": [],
                "tests_recommended": [],
            }
        )
    else:
        _write_result(
            {
                "verdict": "approve",
                "summary": "looks good",
                "blocking_issues": [],
                "non_blocking_issues": [],
                "required_fixes": [],
                "tests_recommended": [],
            }
        )

elif role == "timeout":
    delay = float(os.environ.get("TIMEOUT_SECONDS", "2"))
    time.sleep(delay)
    _write_result({"verdict": "approve", "summary": "too late", "blocking_issues": [], "non_blocking_issues": [], "required_fixes": [], "tests_recommended": []})

else:
    _write_result({"status": "completed"})
""",
        encoding="utf-8",
    )
    script.chmod(0o755)
